# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'development:
developement:
  adapter: mysql2
  encoding: utf8
  database: dev-db
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: test-db
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: prod-db
  pool: 5
  timeout: 5000